export const classes = [
    { "label": "Object", "type": "class", "info": "Base object type" },
    { "label": "Function", "type": "class", "info": "Function constructor" },
    { "label": "Boolean", "type": "class", "info": "Boolean wrapper" },
    { "label": "Symbol", "type": "class", "info": "Symbol primitive type" },
    { "label": "Error", "type": "class", "info": "Generic error" },
    { "label": "EvalError", "type": "class", "info": "Eval error" },
    { "label": "RangeError", "type": "class", "info": "Out-of-range error" },
    { "label": "ReferenceError", "type": "class", "info": "Invalid reference error" },
    { "label": "SyntaxError", "type": "class", "info": "Syntax error" },
    { "label": "TypeError", "type": "class", "info": "Type mismatch error" },
    { "label": "URIError", "type": "class", "info": "Malformed URI error" },
    { "label": "Number", "type": "class", "info": "Number wrapper" },
    { "label": "BigInt", "type": "class", "info": "Arbitrary-precision integers" },
    { "label": "String", "type": "class", "info": "String wrapper" },
    { "label": "Array", "type": "class", "info": "Array wrapper" },
    { "label": "Map", "type": "class", "info": "Key-value map" },
    { "label": "Set", "type": "class", "info": "Unique value set" },
    { "label": "WeakMap", "type": "class", "info": "Weak key-value map" },
    { "label": "WeakSet", "type": "class", "info": "Weak value set" },
    { "label": "Date", "type": "class", "info": "Date and time" },
    { "label": "RegExp", "type": "class", "info": "Regular expression" },
    { "label": "Promise", "type": "class", "info": "Asynchronous operation" },
    { "label": "Math", "type": "variable", "info": "Math utilities" },
    { "label": "JSON", "type": "variable", "info": "JSON utilities" },
    { "label": "console", "type": "variable", "info": "Console logging interface" },
    { "label": 'log', "type": 'function', "info": 'Print something on the console' },
    { "label": 'error', "type": 'function', "info": 'Print an error on the console' },
    { "label": 'warning', "type": 'function', "info": 'Print a warning on the console' },
    { "label": 'info', "type": 'function', "info": 'Clear the console' },
    { "label": 'clear', "type": 'function', "info": 'Clear the console' },
    { "label": "Intl", "type": "variable", "info": "Internationalization API" },
    { "label": "Reflect", "type": "variable", "info": "Reflection API" },
    { "label": "Proxy", "type": "class", "info": "Proxy object for customization" },
    { "label": "ArrayBuffer", "type": "class", "info": "Raw binary data buffer" },
    { "label": "Uint8Array", "type": "class", "info": "Typed array" },
    { "label": "Int8Array", "type": "class", "info": "Typed array" },
    { "label": "Uint16Array", "type": "class", "info": "Typed array" },
    { "label": "Int16Array", "type": "class", "info": "Typed array" },
    { "label": "Uint32Array", "type": "class", "info": "Typed array" },
    { "label": "Int32Array", "type": "class", "info": "Typed array" },
    { "label": "Float32Array", "type": "class", "info": "Typed array" },
    { "label": "Float64Array", "type": "class", "info": "Typed array" },
    { "label": "DataView", "type": "class", "info": "Low-level binary data view" },
    { "label": "BigInt64Array", "type": "class", "info": "Typed array" },
    { "label": "BigUint64Array", "type": "class", "info": "Typed array" }
]